
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr
# خفض الذاكرة لتقليل احتمالات Timeout أثناء البناء
org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
# إيقاف الـ parallel build مؤقتاً عشان ميسحبش رامات كتير
org.gradle.parallel=false
org.gradle.workers.max=1

# استخدام الـ configuration on demand
org.gradle.configureondemand=true
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
android.dexOptions.javaMaxHeapSize=1536m