// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd-Gp-Gpa8zOFXAyy9ADOno6XScCnKHLU',
    appId: '1:299138072360:web:76e9487db2944e2a369a1d',
    messagingSenderId: '299138072360',
    projectId: 'waslny-captain-2026',
    authDomain: 'waslny-captain-2026.firebaseapp.com',
    storageBucket: 'waslny-captain-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9UOQ6fsx_YTBzE7e4x-2s64EAux0fAFA',
    appId: '1:299138072360:android:74fa461847d16df6369a1d',
    messagingSenderId: '299138072360',
    projectId: 'waslny-captain-2026',
    storageBucket: 'waslny-captain-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw0btM97Y1Z6AwhFb2yXxUPYDvjUJD_QM',
    appId: '1:299138072360:ios:ee3bb501edd517fb369a1d',
    messagingSenderId: '299138072360',
    projectId: 'waslny-captain-2026',
    storageBucket: 'waslny-captain-2026.firebasestorage.app',
    iosBundleId: 'com.example.waslnyCaptain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw0btM97Y1Z6AwhFb2yXxUPYDvjUJD_QM',
    appId: '1:299138072360:ios:ee3bb501edd517fb369a1d',
    messagingSenderId: '299138072360',
    projectId: 'waslny-captain-2026',
    storageBucket: 'waslny-captain-2026.firebasestorage.app',
    iosBundleId: 'com.example.waslnyCaptain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd-Gp-Gpa8zOFXAyy9ADOno6XScCnKHLU',
    appId: '1:299138072360:web:c7b7e4829e29eedb369a1d',
    messagingSenderId: '299138072360',
    projectId: 'waslny-captain-2026',
    authDomain: 'waslny-captain-2026.firebaseapp.com',
    storageBucket: 'waslny-captain-2026.firebasestorage.app',
  );
}
