// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_PVbJrUmVATL_7SiWFi2o1zXpe5Zz2p0',
    appId: '1:13729961462:web:df8539ec4ae1abb7d8a3d7',
    messagingSenderId: '13729961462',
    projectId: 'waslny-2a614',
    authDomain: 'waslny-2a614.firebaseapp.com',
    storageBucket: 'waslny-2a614.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_PVbJrUmVATL_7SiWFi2o1zXpe5Zz2p0',
    appId: '1:13729961462:android:df8539ec4ae1abb7d8a3d7',
    messagingSenderId: '13729961462',
    projectId: 'waslny-2a614',
    storageBucket: 'waslny-2a614.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_PVbJrUmVATL_7SiWFi2o1zXpe5Zz2p0',
    appId: '1:13729961462:ios:df8539ec4ae1abb7d8a3d7',
    messagingSenderId: '13729961462',
    projectId: 'waslny-2a614',
    storageBucket: 'waslny-2a614.firebasestorage.app',
    iosBundleId: 'com.waslny.captain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_PVbJrUmVATL_7SiWFi2o1zXpe5Zz2p0',
    appId: '1:13729961462:ios:df8539ec4ae1abb7d8a3d7',
    messagingSenderId: '13729961462',
    projectId: 'waslny-2a614',
    storageBucket: 'waslny-2a614.firebasestorage.app',
    iosBundleId: 'com.waslny.captain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_PVbJrUmVATL_7SiWFi2o1zXpe5Zz2p0',
    appId: '1:13729961462:web:df8539ec4ae1abb7d8a3d7',
    messagingSenderId: '13729961462',
    projectId: 'waslny-2a614',
    authDomain: 'waslny-2a614.firebaseapp.com',
    storageBucket: 'waslny-2a614.firebasestorage.app',
  );
}
